### ISSUE TITLE
[UI] Graph not plotted on clicking "Get Data" for "NEXRAD data"

### ISSUE THREAD

**Issue by bhaktinarvekar** [airavata-courses/Yoda#106]

**Comment by AnshulV98** [comment]
Faced the same issue

**Comment by gouthamgopal** [comment]
@bhaktinarvekar @AnshulV98 The page is not made to display the data. The created jobs and their details are handled in the activities tab. Have handled the miscommunication by adding a redirection link to the activities tab.

**Comment by gouthamgopal** [comment]
#110 Issue is fixed with the code factoring done for this issue.

**Comment by gouthamgopal** [comment]
@bhaktinarvekar  Please re-test and close the issue.
@AnshulV98  Please check and confirm from your side as well.
