### ISSUE TITLE
No Get Data Functioning

### ISSUE THREAD

**Issue by sanyam1997** [airavata-courses/Yoda#204]
I was able to access the Get Data initially. But now when I am trying it is showing me the same error as the one I was facing for NexRad Data. Seems like some connection in the back is getting disconnected for multiple requests or maybe this is nothing but
![Screenshot from 2020-03-20 17-40-27](https://user-images.githubusercontent.com/19321068/77208540-6a75c180-6ad2-11ea-9891-8e77323ed32f.png)
 downtime for the Services.

**Comment by tanvithote** [comment]
We have fixed the real-time issue now. Please re-test and close the issue if resolved.

**Comment by sanyam1997** [comment]
The get data is functional now.
