### ISSUE TITLE
Not able to view the real-time weather data request in http://149.165.171.52:30000/activities

### ISSUE THREAD

**Issue by CleverParty** [airavata-courses/Yoda#208]

**Comment by CleverParty** [comment]
<img width="1076" alt="Screen Shot 2020-03-20 at 10 12 35 PM" src="https://user-images.githubusercontent.com/22660225/77217334-0c5bd500-6af8-11ea-9591-36418958888b.png">
The activities seem to be displayed now

**Comment by gouthamgopal** [comment]
Hi @CleverParty,

The activities section is just to maintain, the user requests for the long running nexrad job and not for the spontaneous realtime data check. But, that can be added as an enhancement and will be a good to have feature.

We shall be tackling that in the coming days.

Regards,
Goutham Gopal

**Comment by CleverParty** [comment]
commit has been verified.
The activities section now reflects the real-time values.
