### ISSUE TITLE
No auto-deploy scripts

### ISSUE THREAD

**Issue by sanyam1997** [airavata-courses/Yoda#210]
In the following section of the wiki, no scripts have been added so far.

**Comment by gouthamgopal** [comment]
Hi @sanyam1997 ,

We were on the process of generating the auto-deploy scripts, so as to facilitate deployment of the whole website from scratch on your own.
We have set it up now and you can reference it from: [Auto Setup](https://github.com/airavata-courses/Yoda/wiki/Auto-Deploy-Scripts).

Please feel free to check it out and let us know of any improvements.
